debug_mode: false #may post lots of spam

pvp: true
pvp_bypass: false # If true, admins can attack other victims even with pvp turned off
whitelist_active: false
no_fall: false
max_itemgive_amount: 250

tpa_active: true
petition_active_for: 60 # in seconds
save_back_when_tpa: true

back_active: true
back_encrypt_mode: 0 #0 None, 1 Basic, 2 Advanced | WARNING: changing the mode may interfer with saved backs.
add_encrypt_mode_to_save: true
delay_onback: 100 #Ticks

# only for discordSRV compability
# on discord srv you may also config this. Example: (Around line 89 config.yml on DiscordSRV)
# UseModernPaperChatEvent: true
discord_adminchat_channel: "CHANNELID"